const fs = require('fs');
let file = fs.readFileSync('src/app/seguimiento-ventas/agenda-cristina/page.tsx', 'utf8');

// HTML template columns
file = file.replace(/<th>Ventas<\/th>\r?\n\s*<th>Llamadas<\/th>\r?\n\s*<th>MLPs<\/th>\r?\n\s*<th>Demos<\/th>/g, '<th>Campañas</th><th>Clientes Propios</th><th>Dispositivos</th><th>BAF</th><th>Repos</th><th>BD Salva</th><th>Competencia</th>');
file = file.replace(/<td style="text-align:center;">\$\{ent\.ventas\|\|0\}<\/td>\r?\n\s*<td style="text-align:center;">\$\{ent\.visitas\|\|0\}<\/td>\r?\n\s*<td style="text-align:center;">\$\{ent\.teams\|\|0\}<\/td>\r?\n\s*<td style="text-align:center;">\$\{ent\.demos\|\|0\}<\/td>/g, '<td style="text-align:center;">${ent.campanas||0}</td><td style="text-align:center;">${ent.clientesPropios||0}</td><td style="text-align:center;">${ent.dispositivos||0}</td><td style="text-align:center;">${ent.baf||0}</td><td style="text-align:center;">${ent.repos||0}</td><td style="text-align:center;">${ent.bdSalva||0}</td><td style="text-align:center;">${ent.competencia||0}</td>');

// Excel format
file = file.replace(/const summaryText = `Ventas: \$\{weekVts\}\\nLlamadas: \$\{weekVis\}\\nMLPs: \$\{weekTms\}\\nDemos: \$\{weekDms\}`/g, 'const summaryText = `Campañas: ${weekCampanas}\\nClientes Propios: ${weekClientes}\\nDispositivos: ${weekDisp}\\nBAF: ${weekBaf}\\nRepos: ${weekRepos}\\nBD Salva: ${weekBdSalva}\\nCompetencia: ${weekComp}`');
file = file.replace(/const cellText = `V: \$\{ent\.ventas\|\|0\} \| Ll: \$\{ent\.visitas\|\|0\} \| M: \$\{ent\.teams\|\|0\} \| D: \$\{ent\.demos\|\|0\}\\n\$\{ent\.observaciones \|\| ''\}`/g, 'const cellText = `C: ${ent.campanas||0} | CP: ${ent.clientesPropios||0} | D: ${ent.dispositivos||0} | B: ${ent.baf||0} | R: ${ent.repos||0} | BD: ${ent.bdSalva||0} | CO: ${ent.competencia||0}\\n${ent.observaciones || \'\'}`');

// Edit modal HTML
file = file.replace(/<div style=\{\{ display: 'grid', gridTemplateColumns: 'repeat\(4, 1fr\)', gap: 12 \}\}>[\s\S]*?(?=<div>\r?\n\s*<label style=\{\{ display: 'block', fontSize: 12, fontWeight: 700, color: 'var\(--text-main\)', marginBottom: 4 \}\}>\r?\n\s*Observaciones Cortas)/, `<div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12 }}>
                                <div><label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: 'var(--text-main)', marginBottom: 4 }}><span style={{ color: '#16a34a' }}>🎯 Llamadas Campañas</span></label><input type="number" min="0" value={editForm.campanas} onChange={e => setEditForm(prev => ({ ...prev, campanas: Number(e.target.value) }))} style={{ width: '100%', padding: '8px 12px', border: '1px solid var(--border-light)', borderRadius: 6, fontSize: 14, background: 'var(--bg-input)' }} /></div>
                                <div><label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: 'var(--text-main)', marginBottom: 4 }}><span style={{ color: '#0ea5e9' }}>📞 Llamadas Clientes Propios</span></label><input type="number" min="0" value={editForm.clientesPropios} onChange={e => setEditForm(prev => ({ ...prev, clientesPropios: Number(e.target.value) }))} style={{ width: '100%', padding: '8px 12px', border: '1px solid var(--border-light)', borderRadius: 6, fontSize: 14, background: 'var(--bg-input)' }} /></div>
                                <div><label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: 'var(--text-main)', marginBottom: 4 }}><span style={{ color: '#8b5cf6' }}>💻 Llamadas Dispositivos</span></label><input type="number" min="0" value={editForm.dispositivos} onChange={e => setEditForm(prev => ({ ...prev, dispositivos: Number(e.target.value) }))} style={{ width: '100%', padding: '8px 12px', border: '1px solid var(--border-light)', borderRadius: 6, fontSize: 14, background: 'var(--bg-input)' }} /></div>
                                <div><label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: 'var(--text-main)', marginBottom: 4 }}><span style={{ color: '#d97706' }}>📺 Llamadas BAF</span></label><input type="number" min="0" value={editForm.baf} onChange={e => setEditForm(prev => ({ ...prev, baf: Number(e.target.value) }))} style={{ width: '100%', padding: '8px 12px', border: '1px solid var(--border-light)', borderRadius: 6, fontSize: 14, background: 'var(--bg-input)' }} /></div>
                                <div><label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: 'var(--text-main)', marginBottom: 4 }}><span style={{ color: '#ec4899' }}>📦 Llamadas Repos</span></label><input type="number" min="0" value={editForm.repos} onChange={e => setEditForm(prev => ({ ...prev, repos: Number(e.target.value) }))} style={{ width: '100%', padding: '8px 12px', border: '1px solid var(--border-light)', borderRadius: 6, fontSize: 14, background: 'var(--bg-input)' }} /></div>
                                <div><label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: 'var(--text-main)', marginBottom: 4 }}><span style={{ color: '#ef4444' }}>🗃️ BD Salva</span></label><input type="number" min="0" value={editForm.bdSalva} onChange={e => setEditForm(prev => ({ ...prev, bdSalva: Number(e.target.value) }))} style={{ width: '100%', padding: '8px 12px', border: '1px solid var(--border-light)', borderRadius: 6, fontSize: 14, background: 'var(--bg-input)' }} /></div>
                                <div><label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: 'var(--text-main)', marginBottom: 4 }}><span style={{ color: '#3f6212' }}>⚔️ Competencia</span></label><input type="number" min="0" value={editForm.competencia} onChange={e => setEditForm(prev => ({ ...prev, competencia: Number(e.target.value) }))} style={{ width: '100%', padding: '8px 12px', border: '1px solid var(--border-light)', borderRadius: 6, fontSize: 14, background: 'var(--bg-input)' }} /></div>
                            </div>\n`);

fs.writeFileSync('src/app/seguimiento-ventas/agenda-cristina/page.tsx', file);
